- Red y DNS:
    - MXToolbox:
        - abbr: MX
          href: https://mxtoolbox.com/SuperTool.aspx
          description: DNS, MX, blacklist, SMTP y TCP

    - SSL Labs:
        - abbr: SL
          href: https://www.ssllabs.com/ssltest/
          description: Análisis SSL/TLS de servicios públicos

- Seguridad:
    - VirusTotal:
        - abbr: VT
          href: https://www.virustotal.com/gui/home/url
          description: Analizar URLs y archivos sospechosos

    - URLScan:
        - abbr: US
          href: https://urlscan.io/
          description: Analizar comportamiento de sitios web

    - Webhook.site:
        - abbr: WH
          href: https://webhook.site/
          description: Capturar y depurar webhooks

    - Regex101:
        - abbr: RX
          href: https://regex101.com/
          description: Probar y depurar expresiones regulares

    - JSONLint:
        - abbr: JS
          href: https://jsonlint.com/
          description: Validar y reparar JSON
