services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      HOMEPAGE_ALLOWED_HOSTS: "192.168.1.117:3000,homepage.vortex42.local"

    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
